# Generated by Django 2.2.22 on 2021-05-11 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='titles',
            new_name='title',
        ),
    ]
